FROM node:18.14.2-slim as build

# make the 'app' folder the current working directory
WORKDIR /app/front
COPY package*.json ./


RUN npm install

COPY . .
RUN npm run build


#FROM nginx:1.21.0-alpine
#COPY --from=build /app/dist /usr/share/nginx/html
#COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
